version: "3.8"

services:
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    container_name: task-queue-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  # Backend Service
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    container_name: task-queue-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
